org: serverlessmaxim
app: product-service-aws-shop
service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  httpApi:
    cors: true

functions:
  function1:
    handler: index.handler
  getProductsList:
    handler: handlers/getProductsList.handler
    events:
      - httpApi:
          path: /products
          method: GET
  getProductsById:
    handler: handlers/getProductsById.handler
    events:
      - httpApi:
          path: /products/{productId}
          method: GET
          
